### PR TITLE
#18 - add support for multiple export formats at the same time

### PR DESCRIPTION
**Pull request by csandersdev**
In response to #18, adding support for multiple simultaneous export formats. Users provide the list of target formats in the X-TargetFormat header as a comma-separated list per RFC2616. Glassfish doesn't deal well with parsing this format, though, so we had to roll our own parsing for the list. See https://github.com/jersey/jersey/issues/2436 for details. 

When requesting multiple formats, the output will be a MIME multipart request with multiple body parts mapped to the name of the input request, each with a content disposition that matches the requested format.

### CODE REVIEW

**Comment by cmoesel** [comment]
@brynrhodes @JPercival -- do you actively use this service and if so, do you want to review this PR?  Or should I review it on my own?

**Comment by brynrhodes** [comment]
We do use this in support of the cql-runner website, I've pulled it locally and am reviewing now

**Review by brynrhodes — APPROVED** [review]
Looks good to me, builds locally, tests pass.

**Review by cmoesel — APPROVED** [review]
Looks good here to.  Thanks for the PR.  The only thing better than a PR from an outside contributor is a PR from an outside contributor with unit tests!  So thank you for that!

**Comment by cmoesel** [comment]
This feature was included in the [1.4.9 release](https://github.com/cqframework/cql-translation-service/releases/tag/v1.4.9).  Thanks again, @csandersdev!

**Pull request merged**
